# Generated by Django 2.2.2 on 2019-06-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_ip',
            field=models.CharField(default='127.0.0.1', max_length=25),
        ),
    ]
