# Generated by Django 2.2.2 on 2019-06-30 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0002_user_client_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 22, 37, 11, 21939, tzinfo=utc), verbose_name='Last Dark API request date'),
        ),
    ]
