# Generated by Django 2.2.2 on 2019-06-30 23:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0003_auto_20190630_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 23, 9, 35, 939488, tzinfo=utc), verbose_name='Last Dark API request date'),
        ),
    ]
